change db location

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -42,58 +42,59 @@ jobs:
       with:
         fetch-depth: 2
 
-    # # - uses: actions/download-artifact@v3
-    # #   with:
-    # #     name: graphql-latest
-    # #     path: /tmp/graphql-previous 
-
-    # # Initializes the CodeQL tools for scanning.
-    # - name: Initialize CodeQL
-    #   uses: github/codeql-action/init@v2
+    # - uses: actions/download-artifact@v3
     #   with:
-    #     packs: nettrino/nomod
-    #     languages: ${{ matrix.language }}
-    #     # If you wish to specify custom queries, you can do so here or in a config file.
-    #     # By default, queries listed here will override any specified in a config file.
-    #     # Prefix the list here with "+" to use these queries and those in the config file.
-    #     
-    #     # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-    #     # queries: security-extended,security-and-quality
+    #     name: graphql-latest
+    #     path: /tmp/graphql-previous 
 
-    #     
-    # # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
-    # # If this step fails, then you should remove it and run the build manually (see below)
-    # - name: Autobuild
-    #   uses: github/codeql-action/autobuild@v2
+    # Initializes the CodeQL tools for scanning.
+    - name: Initialize CodeQL
+      uses: github/codeql-action/init@v2
+      with:
+        packs: nettrino/nomod
+        languages: ${{ matrix.language }}
+        # If you wish to specify custom queries, you can do so here or in a config file.
+        # By default, queries listed here will override any specified in a config file.
+        # Prefix the list here with "+" to use these queries and those in the config file.
+        
+        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+        # queries: security-extended,security-and-quality
 
-    # # ℹ️ Command-line programs to run using the OS shell.
-    # # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+        
+    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
+    # If this step fails, then you should remove it and run the build manually (see below)
+    - name: Autobuild
+      uses: github/codeql-action/autobuild@v2
 
-    # #   If the Autobuild fails above, remove it and uncomment the following three lines. 
-    # #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
+    # ℹ️ Command-line programs to run using the OS shell.
+    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
 
-    # # - run: |
-    # #   echo "Run, Build Application using script"
-    # #   ./location_of_script_within_repo/buildscript.sh
+    #   If the Autobuild fails above, remove it and uncomment the following three lines. 
+    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
 
-    # - name: Perform CodeQL Analysis
-    #   uses: github/codeql-action/analyze@v2
-    #   with:
-    #     category: "/language:${{matrix.language}}"
+    # - run: |
+    #   echo "Run, Build Application using script"
+    #   ./location_of_script_within_repo/buildscript.sh
 
-    # - name: Copy previous analysis results
-    #   run: cp /home/runner/work/_temp/codeql_databases/python/results/nettrino/nomod/transitive.bqrs /tmp/transitive.bqrs
-    # 
-    # - name: Checkout previous commit
-    #   run: git checkout HEAD~1
-    # 
-    # - name: Perform CodeQL Analysis on previous state
-    #   uses: github/codeql-action/analyze@v2
-    #   with:
-    #     category: "previous_commit"
+    - name: Perform CodeQL Analysis
+      uses: github/codeql-action/analyze@v2
+      with:
+        category: "/language:${{matrix.language}}"
 
-    # - name: See if there's a diff
-    #   run: diff /home/runner/work/_temp/codeql_databases/python/results/nettrino/nomod/transitive.bqrs /tmp/transitive.bqrs
+    - name: Copy previous analysis results
+      run: cp /home/runner/work/_temp/codeql_databases/python/results/nettrino/nomod/transitive.bqrs /tmp/transitive.bqrs
+    
+    - name: Checkout previous commit
+      run: git checkout HEAD~1
+    
+    - name: Perform CodeQL Analysis on previous state
+      uses: github/codeql-action/analyze@v2
+      with:
+        db-location: /tmp/newdb_loc
+        category: "previous_commit"
+
+    - name: See if there's a diff
+      run: diff /tmp/newdb_loc/python/results/nettrino/nomod/transitive.bqrs /tmp/transitive.bqrs
 
     - name: assign reviewer
       uses: LongOddCode/assign-reviewer@0.2.2
@@ -122,4 +123,6 @@ jobs:
         # Your business logic.
         # Required.
         run: |
-          echo '::set-output name=TELEMETRY_RESULT::true'
+          if ! diff -q /home/runner/work/_temp/codeql_databases/python/results/nettrino/nomod/transitive.bqrs /tmp/transitive.bqrs; then
+            echo '::set-output name=TELEMETRY_RESULT::true'
+          fi
